name: trigger jenkins job
on:
  pull_request:
    branches: [ "develop" ]
    types: [closed]

jobs:
 
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_SERVER }}
        user: "camlump"
        token: ${{ secrets.JENKINS_PAT }}
        job: "testPipeline"
